### PR TITLE
12 enable travis ci

### PR DESCRIPTION
**Pull request by patrick-hebner**

### CODE REVIEW

**Comment by patrick-hebner** [comment]
Sorry for the long commit list. I just wanted to try a rebase instead of a merge, but this caused all commits to be pushed again.

**Comment by patrick-hebner** [comment]
Your meaning to the travis config would be welcome because I'm not that experienced in travis

**Comment by flashback2k14** [comment]
No Problem. Please add Travis Banner to readme.

**Comment by flashback2k14** [comment]
If it Run the Tests than All is good for me. :-)

**Comment by patrick-hebner** [comment]
I added the travis badge for the master branch

**Pull request merged**
